# Generated by Django 3.2.7 on 2022-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
